name: bloomen
title: Bloomen
description: Integration with the Bloomen project
infoUrl: http://bloomen.io/
maintainer: Kendraio
supportUrl: http://kendra.io
uploads: true
swagger: extra/bloomen/api-docs.json

database:
  - extra/bloomen/schemas/user.schema.json
  - extra/bloomen/schemas/photo.schema.json

forms:
  musicalWork:
    jsonSchema: extra/bloomen/schemas/musicalWork.schema.json
    uiSchema: extra/bloomen/schemas/musicalWork.ui.json
  soundRecording:
    jsonSchema: extra/bloomen/schemas/soundRecording.schema.json
    uiSchema: extra/bloomen/schemas/soundRecording.ui.json
  user:
    jsonSchema: extra/bloomen/schemas/user.schema.json
    uiSchema: extra/bloomen/schemas/user.ui.json
  photo:
    jsonSchema: extra/bloomen/schemas/photo.schema.json
    uiSchema: extra/bloomen/schemas/photo.ui.json

queries:
  - extra/bloomen/queries/listSoundRecordings.json
  - extra/bloomen/queries/listMusicalWorks.json
  - extra/bloomen/queries/chartReleases.json

configs:
  - extra/bloomen/configs/listSoundRecordings.json
  - extra/bloomen/configs/listMusicalWorks.json
  - extra/bloomen/configs/chartReleases.json
  - extra/bloomen/configs/editSoundRecording.json
  - extra/bloomen/configs/messageExample.json
  - extra/bloomen/configs/templateExample.json
  - extra/bloomen/configs/dialogExample.json
  - extra/bloomen/configs/bloomenApiJwt-musicalWorks.json
  - extra/bloomen/configs/bloomenApiJwt-soundRecordings.json
  - extra/bloomen/configs/bloomenApiJwt-exportMusicalWorks.json
  - extra/bloomen/configs/importMusicalWorks.json
