name: unsplash
title: Unsplash
description: Beautiful high quality free images and photos you can download and use for any project. No attribution required.
infoUrl: https://unsplash.com/
maintainer: Kendraio
supportUrl: http://kendra.io
uploads: true
swagger: extras/unsplash/swagger.json
